### ISSUE TITLE
Feature Request: Tumor soll im DiagReport als primär markiert werden können

### ISSUE THREAD

**Issue by ByteGnome** [vision-zero-oncology/GOLD#27]

**Comment by johannes-kast-mint** [comment]
Die Markierung geht nach unserem aktuellen Konzept so:

Die Markierung als "Primär" erfolgt einem gewissen Befundungsvorgang das bilden wir mit den ReadProcedures ab. Ein Tumor hat in unserem modell eine BodyStructure und ggf. eine Observation (e.g. TumorMeasurement) im DiagReport. Die eigentliche Markierung ist dann eine spezifische Observation die eine partOf Referenz zur ReadProcedure hat und einen focus auf die BodyStructure.


Im falle von TNM sieht das dann so aus:
![Image](https://github.com/vision-zero-oncology/GOLD/assets/92932333/b7f0b72c-9d32-466b-b566-cff0d4e1e11c)

Die TNM ReadProcedure hat ein ValueSet um welche TNM Version / Entität es sich handelt. Die TNM Category ist eine Observation mit dem ValueSet für Target (primär Tumore) / Nodules / Metastasis

**Comment by johannes-kast-mint** [comment]
Das ist meiner Meinung nach abgeschlossen. Und so wie oben abgebildet.
