### ISSUE TITLE
Recherche für Profile Pathologie

### ISSUE THREAD

**Issue by ByteGnome** [vision-zero-oncology/GOLD#30]
Würde das [MII Modul](https://simplifier.net/medizininformatikinitiative-modulpathologie) passen?

**Comment by mila-lysyakova** [comment]
Recherche abgeschlossen -> Zusammenfassung in Arbeit

**Comment by ByteGnome** [comment]
Das MII Modul ist nach unserem bisherigen Wissensstand die einzige Spezifikation in DE für einen strukturierten pathologischen Befundbericht. (geschaut/gefragt wurde bei gematik und mio42)
