### ISSUE TITLE
Für Medication prüfen ob Tumor Referenz notwendig ist

### ISSUE THREAD

**Issue by johannes-kast-mint** [vision-zero-oncology/GOLD#35]

**Comment by mila-lysyakova** [comment]
Wenn Immuntherapie und Stammzelltherapie als Medications abgebildet werden, sollte ein Verweis auf genomisches Profil, also Specimen oder Sequenzierung-Observation (und darüber Tumor) vorhanden sein. Wir träumen von personalisierten Therapien! Außerdem mutieren Tumoren während/mit/durch Therapien, daher ist es sehr wichtig!

**Comment by julsas** [comment]
http://hl7.org/fhir/us/mcode/StructureDefinition-mcode-cancer-related-medication-administration.html
reasonReference -> Condition

**Comment by julsas** [comment]
[supportingInformation](http://hl7.org/fhir/R4/medicationadministration-definitions.html#MedicationAdministration.supportingInformation) -> BodyStructure

("derivedFrom")
