### ISSUE TITLE
Wie wollen wir mit Internationalisierung umgehen

### ISSUE THREAD

**Issue by johannes-kast-mint** [vision-zero-oncology/GOLD#40]
Hypothese:
* Englisch ist die Hauptsprache
* Im einzelnen kann es aber notwendig sein, dass wir deutsche Spezfiika extra definieren.

**Comment by mila-lysyakova** [comment]
Auf der Entwicklungsebene ist Englisch wohl besser, entsprechend der Konvention
Auf Implementierungsebene sollten wir uns an deutsche Nutzer und Vorschriften des BfARMs orientieren, also Deutsch im IG wünschenswert
